import { useState } from "react";
import { Calendar } from "lucide-react";
import { AnimatePresence, motion } from "framer-motion";

import useVendorSearch, {
  VendorSearchResult,
} from "@/features/VendorSearch/hooks/useVendorSearch";
import useCreateBooking, { BookingResult } from "../hooks/useCreateBooking";
import BookingConfirmModal from "../components/BookingConfirmModal";
import { toast } from "sonner";
import useActiveCategories from "@/features/VendorSearch/hooks/useActiveCategories";
import { MagneticDots } from "@/components/common/MagneticDots";
import VendorPickerModal from "../components/VendorPickerModal";
import useCategoryOfferings from "@/features/MyProfile/hooks/useCategoryOfferings";
import { getNextHourHHMM } from "@/helpers/timeHelpers";
import RequestEditForm, {
  URGENCY_OPTIONS,
} from "../components/RequestEditForm";
import RequestPreview from "../components/RequestPreview";

const VIEW_EASE = [0.16, 1, 0.3, 1] as const;
const viewMotionProps = {
  initial: { opacity: 0, y: 8, filter: "blur(8px)" },
  animate: { opacity: 1, y: 0, filter: "blur(0px)" },
  exit: { opacity: 0, y: 8, filter: "blur(8px)" },
  transition: { duration: 0.35, ease: VIEW_EASE },
};

export default function BookingRequestPage() {
  const {
    results: vendorResults,
    loading: vendorsLoading,
    search: searchVendors,
  } = useVendorSearch();
  const { submitting, submitBooking } = useCreateBooking();

  const [categoryCode, setCategoryCode] = useState("");
  const { categories } = useActiveCategories();
  const categoryLabel =
    categories.find((c) => c.code === categoryCode)?.name ?? categoryCode;

  const [selectedVendor, setSelectedVendor] =
    useState<VendorSearchResult | null>(null);
  const [showVendorPicker, setShowVendorPicker] = useState(false);

  const [title, setTitle] = useState("");
  const [urgency, setUrgency] = useState("");

  const [address, setAddress] = useState("");
  const [locality, setLocality] = useState("");
  const [city, setCity] = useState("");
  const [state, setState] = useState("");
  const [pincode, setPincode] = useState("");

  const [serviceOfferingIds, setServiceOfferingIds] = useState<string[]>([]);
  const { offeringsByCategory } = useCategoryOfferings(
    categoryCode ? [categoryCode] : [],
  );
  const categoryOfferings = categoryCode
    ? (offeringsByCategory[categoryCode] ?? [])
    : [];

  const [preferredDate, setPreferredDate] = useState(() => {
    const today = new Date();
    const y = today.getFullYear();
    const m = String(today.getMonth() + 1).padStart(2, "0");
    const d = String(today.getDate()).padStart(2, "0");
    return `${y}-${m}-${d}`;
  });
  const [preferredTime, setPreferredTime] = useState(getNextHourHHMM);
  const [estimatedBudget, setEstimatedBudget] = useState("");

  const [confirmedBooking, setConfirmedBooking] =
    useState<BookingResult | null>(null);
  const [showConfirm, setShowConfirm] = useState(false);
  const [customRequirement, setCustomRequirement] = useState("");
  const [bookingMode, setBookingMode] = useState<
    "specific" | "broadcast" | null
  >(null);
  const [view, setView] = useState<"form" | "preview">("form");

  function openVendorPicker() {
    if (!categoryCode) {
      toast.error("Pick a category first - vendor results depend on it.");
      return;
    }
    searchVendors({ category: categoryCode });
    setShowVendorPicker(true);
  }

  const autoGeneratedSummary =
    serviceOfferingIds.length > 0
      ? `${categoryOfferings
          .filter((o) => serviceOfferingIds.includes(o.id))
          .map((o) => o.name)
          .join(", ")}.`
      : "";

  const combinedDescription = [customRequirement.trim(), autoGeneratedSummary]
    .filter(Boolean)
    .join("\n\n");

  function handleContinueToPreview() {
    if (
      !categoryCode ||
      !title ||
      !combinedDescription ||
      !urgency ||
      !address ||
      !locality ||
      !city ||
      !state ||
      !pincode ||
      !preferredDate
    ) {
      toast.error("Fill in all required fields before submitting.");
      return;
    }
    setView("preview");
  }

  async function handleConfirmSubmit() {
    const booking = await submitBooking({
      categoryCode,
      vendorId: selectedVendor?.vendorId ?? "",
      title,
      description: combinedDescription,
      urgency,
      address,
      locality,
      city,
      state,
      pincode,
      serviceOfferingIds,
      preferredDate,
      preferredTime,
      estimatedBudget,
    });

    if (booking) {
      setConfirmedBooking(booking);
      setShowConfirm(true);
    } else {
      toast.error("Couldn't submit your request. Try again.");
    }
  }

  function handleSelectSpecific() {
    const enteringSpecificMode = bookingMode !== "specific";
    setBookingMode("specific");
    if (enteringSpecificMode && !selectedVendor) openVendorPicker();
  }

  function handleSelectBroadcast() {
    setBookingMode("broadcast");
    setSelectedVendor(null);
  }

  const selectedUrgency = URGENCY_OPTIONS.find((o) => o.code === urgency);

  return (
    <section className="bg-surface p-4 rounded-xl h-fit w-full relative">
      <MagneticDots
        palette="Google"
        intensity={1}
        className="absolute inset-0 h-full w-full"
      />

      <section className="relative z-20">
        <section className="max-w-5xl mx-auto rounded-xl h-full w-full p-8 pt-0 space-y-6 font-sans overflow-x-hidden overflow-y-auto">
          <div className="relative">
            <div
              className="pointer-events-none absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2"
              style={{
                width: "100%",
                height: "100%",
                background:
                  "radial-gradient(ellipse 720px 300px at 50% 48%, rgba(255,255,255,.9), rgba(255,255,255,0) 68%)",
              }}
            />
            <div className="relative z-20">
              <h1 className="text-2xl font-bold text-ink">New Request</h1>
              <p className="text-sm text-ink-muted">
                Tell us what you need and we'll help you connect with the right
                vendor.
              </p>
            </div>
          </div>

          <AnimatePresence mode="wait">
            {view === "form" ? (
              <motion.div key="form" {...viewMotionProps}>
                <RequestEditForm
                  categoryCode={categoryCode}
                  onCategoryChange={(code) => {
                    setCategoryCode(code);
                    setSelectedVendor(null);
                  }}
                  categoryOfferings={categoryOfferings}
                  serviceOfferingIds={serviceOfferingIds}
                  setServiceOfferingIds={setServiceOfferingIds}
                  title={title}
                  setTitle={setTitle}
                  customRequirement={customRequirement}
                  setCustomRequirement={setCustomRequirement}
                  autoGeneratedSummary={autoGeneratedSummary}
                  bookingMode={bookingMode}
                  onSelectSpecific={handleSelectSpecific}
                  onSelectBroadcast={handleSelectBroadcast}
                  selectedVendor={selectedVendor}
                  onChangeVendor={openVendorPicker}
                  onRemoveVendor={() => setSelectedVendor(null)}
                  address={address}
                  setAddress={setAddress}
                  locality={locality}
                  setLocality={setLocality}
                  city={city}
                  setCity={setCity}
                  state={state}
                  setState={setState}
                  pincode={pincode}
                  setPincode={setPincode}
                  preferredDate={preferredDate}
                  setPreferredDate={setPreferredDate}
                  preferredTime={preferredTime}
                  setPreferredTime={setPreferredTime}
                  urgency={urgency}
                  setUrgency={setUrgency}
                  estimatedBudget={estimatedBudget}
                  setEstimatedBudget={setEstimatedBudget}
                  onContinue={handleContinueToPreview}
                />
              </motion.div>
            ) : (
              <motion.div key="preview" {...viewMotionProps}>
                <RequestPreview
                  categoryLabel={categoryLabel}
                  offeringsLabel={autoGeneratedSummary}
                  title={title}
                  requirement={customRequirement.trim()}
                  address={address}
                  locality={locality}
                  city={city}
                  state={state}
                  pincode={pincode}
                  preferredDate={preferredDate}
                  preferredTime={preferredTime}
                  estimatedBudget={estimatedBudget}
                  urgencyLabel={selectedUrgency?.name ?? ""}
                  urgencyDescription={selectedUrgency?.description ?? ""}
                  UrgencyIcon={selectedUrgency?.Icon ?? Calendar}
                  urgencyIconColor={selectedUrgency?.iconColor ?? "text-ink"}
                  urgencyBg={selectedUrgency?.iconBg ?? "bg-surface-page"}
                  vendorName={selectedVendor?.businessName ?? null}
                  submitting={submitting}
                  onBack={() => setView("form")}
                  onEditVendor={() => setView("form")}
                  onSubmit={handleConfirmSubmit}
                />
              </motion.div>
            )}
          </AnimatePresence>

          <VendorPickerModal
            open={showVendorPicker}
            onClose={() => setShowVendorPicker(false)}
            vendors={vendorResults}
            loading={vendorsLoading}
            onConfirm={(vendor) => setSelectedVendor(vendor)}
          />

          <BookingConfirmModal
            open={showConfirm}
            onClose={() => setShowConfirm(false)}
            booking={confirmedBooking}
          />
        </section>
      </section>
    </section>
  );
}
