import { useState } from "react";

import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { ScrollText, Send, ShieldCheck, Users } from "lucide-react";

import useVendorSearch, {
  VendorSearchResult,
} from "@/features/VendorSearch/hooks/useVendorSearch";
import useCreateBooking, { BookingResult } from "../hooks/useCreateBooking";
import BookingConfirmModal from "../components/BookingConfirmModal";
import { toast } from "sonner";
// import useActiveCategories from "@/features/VendorSearch/hooks/useActiveCategories";
import { MagneticDots } from "@/components/common/MagneticDots";

import { SectionCard } from "@/features/MyProfile/components/SectionCard";

import VendorPickerModal from "../components/VendorPickerModal";
import useCategoryOfferings from "@/features/MyProfile/hooks/useCategoryOfferings";
import { MultiSelect } from "@/components/ui/MultiSelect";
import FieldTitle from "@/components/ui/FieldTitle";
import { CategorySelect } from "@/components/common/CategorySelect";
import VendorPickerCard from "../components/VendorPickerCard";

// const URGENCY_OPTIONS = [
//   { code: "FLEXIBLE", name: "Flexible - no rush" },
//   { code: "WITHIN_A_FEW_DAYS", name: "Within a few days" },
//   { code: "URGENT", name: "Urgent - as soon as possible" },
// ];

export default function BookingRequestPage() {
  // const { categories } = useActiveCategories();
  const {
    results: vendorResults,
    loading: vendorsLoading,
    search: searchVendors,
  } = useVendorSearch();
  const { submitting, submitBooking } = useCreateBooking();

  const [categoryCode, setCategoryCode] = useState("");
  const [selectedVendor, setSelectedVendor] =
    useState<VendorSearchResult | null>(null);
  const [showVendorPicker, setShowVendorPicker] = useState(false);

  const [title, setTitle] = useState("");
  // const [description, setDescription] = useState("");
  const [urgency, setUrgency] = useState("");

  const [address, setAddress] = useState("");
  const [locality, setLocality] = useState("");
  const [city, setCity] = useState("");
  const [state, setState] = useState("");
  const [pincode, setPincode] = useState("");

  const [serviceOfferingIds, setServiceOfferingIds] = useState<string[]>([]);

  const { offeringsByCategory } = useCategoryOfferings(
    categoryCode ? [categoryCode] : [],
  );
  const categoryOfferings = categoryCode
    ? (offeringsByCategory[categoryCode] ?? [])
    : [];

  const [preferredDate, setPreferredDate] = useState("");
  const [preferredTime, setPreferredTime] = useState("");

  const [estimatedBudget, setEstimatedBudget] = useState("");

  const [confirmedBooking, setConfirmedBooking] =
    useState<BookingResult | null>(null);
  const [showConfirm, setShowConfirm] = useState(false);

  function openVendorPicker() {
    if (!categoryCode) {
      toast.error("Pick a category first - vendor results depend on it.");
      return;
    }
    searchVendors({ category: categoryCode });
    setShowVendorPicker(true);
  }

  const [customRequirement, setCustomRequirement] = useState("");

  const autoGeneratedSummary =
    serviceOfferingIds.length > 0
      ? `${categoryOfferings
          .filter((o) => serviceOfferingIds.includes(o.id))
          .map((o) => o.name)
          .join(", ")}.`
      : "";

  const combinedDescription = [customRequirement.trim(), autoGeneratedSummary]
    .filter(Boolean)
    .join("\n\n");

  async function handleSubmit() {
    if (
      !categoryCode ||
      !title ||
      !combinedDescription ||
      !urgency ||
      !address ||
      !locality ||
      !city ||
      !state ||
      !pincode ||
      !preferredDate
    ) {
      toast.error("Fill in all required fields before submitting.");
      return;
    }

    const booking = await submitBooking({
      categoryCode,
      vendorId: selectedVendor?.vendorId ?? "",
      title,
      description: combinedDescription,
      urgency,
      address,
      locality,
      city,
      state,
      pincode,
      serviceOfferingIds,
      preferredDate,
      preferredTime,
      estimatedBudget,
    });

    if (booking) {
      setConfirmedBooking(booking);
      setShowConfirm(true);
    } else {
      toast.error("Couldn't submit your request. Try again.");
    }
  }

  const [bookingMode, setBookingMode] = useState<
    "specific" | "broadcast" | null
  >(null);

  function handleSelectSpecific() {
    const enteringSpecificMode = bookingMode !== "specific";
    setBookingMode("specific");
    if (enteringSpecificMode && !selectedVendor) {
      openVendorPicker();
    }
  }

  function handleSelectBroadcast() {
    setBookingMode("broadcast");
    setSelectedVendor(null);
  }

  return (
    <section className="bg-surface p-4 rounded-xl h-fit w-full relative">
      <MagneticDots
        palette="Google"
        intensity={1}
        className="absolute inset-0 h-full w-full"
      />

      <section className="relative z-20">
        <section className="max-w-4xl max-auto rounded-xl h-full w-full p-8 pt-0 space-y-6 font-sans overflow-x-hidden overflow-y-auto">
          <div className="relative">
            <div
              className="pointer-events-none absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2"
              style={{
                width: "100%",
                height: "100%",
                background:
                  "radial-gradient(ellipse 720px 300px at 50% 48%, rgba(255,255,255,.9), rgba(255,255,255,0) 68%)",
              }}
            />
            <div className="relative z-20">
              <h1 className="text-2xl font-bold text-ink-900">
                Request a Booking
              </h1>
              <p className="text-sm text-ink-muted">
                Tell us what you need and we'll help you connect with the right
                vendor.
              </p>
            </div>
          </div>

          <div className="flex flex-col gap-8">
            {/* 1. Service Details */}
            <SectionCard
              title="Service Details"
              iconBg="bg-success/20"
              icon={<span className="text-sm font-semibold">1</span>}
              className="border border-surface-page shadow-md bg-white w-full"
            >
              <div className="flex flex-col gap-1">
                {/* <h2 className="text-sm font-semibold text-ink mb-3">
                  1. Service Details
                </h2> */}
                <div className="grid grid-cols-2 gap-3 mb-3 items-end">
                  <div>
                    <FieldTitle
                      label="Category"
                      htmlFor="category"
                      className="ml-1"
                      isRequired
                    />
                    <CategorySelect
                      value={categoryCode}
                      onChange={(code) => {
                        setCategoryCode(code);
                        setSelectedVendor(null);
                      }}
                      placeholder="Select a category"
                      parentClassName="mt-1.5"
                      containerClassName="py-2 px-3"
                      persona="customer"
                    />
                  </div>
                  <div>
                    <FieldTitle
                      label="Service"
                      htmlFor="service"
                      className="ml-1"
                    />
                    <MultiSelect
                      options={categoryOfferings.map((o) => ({
                        code: o.id,
                        name: o.name,
                      }))}
                      value={serviceOfferingIds}
                      onChange={setServiceOfferingIds}
                      placeholder="Select one or more services"
                      persona="customer"
                      containerClassName="py-2 px-3 mt-1.5"
                      displayChips={false}
                    />
                  </div>

                  {/* <Select
                    options={URGENCY_OPTIONS}
                    value={
                      URGENCY_OPTIONS.find((u) => u.code === urgency)?.name ??
                      ""
                    }
                    onChange={(name) => {
                      const match = URGENCY_OPTIONS.find(
                        (u) => u.name === name,
                      );
                      setUrgency(match?.code ?? "");
                    }}
                    placeholder="Select urgency"
                    persona="customer"
                  /> */}
                </div>

                <section>
                  <FieldTitle
                    label="Request Title"
                    htmlFor="title"
                    className="ml-1"
                    isRequired
                  />
                  <Input
                    id="title"
                    placeholder="E.g. Need electrical wiring for my 2BHK flat"
                    value={title}
                    onChange={(e) => setTitle(e.target.value)}
                    className="mb-3 mt-1.5"
                  />
                </section>

                <section>
                  <FieldTitle
                    label="Describe Your Requirement"
                    htmlFor="description"
                    className="ml-1"
                    isRequired
                  />
                  <Textarea
                    id="description"
                    className="mt-1.5"
                    placeholder="Describe what you need done..."
                    value={customRequirement}
                    onChange={(e) => setCustomRequirement(e.target.value)}
                    maxLength={1000}
                    rows={4}
                  />
                  <p className="text-xs text-ink-muted text-right mt-1">
                    {customRequirement.length}/1000
                  </p>
                  {autoGeneratedSummary && (
                    <div className="mt-2 px-3 py-2 pb-3 rounded-lg bg-brand-blue/5  border-ink-placeholder/50 text-xs text-ink-muted border-2 border-dotted">
                      <section className="flex gap-2 items-center">
                        <div
                          className={`w-8 h-8 rounded-lg flex items-center justify-center bg-brand-blue-deep/5`}
                        >
                          <ScrollText className="text-brand-blue" size={16} />
                        </div>
                        <span className="font-medium text-sm text-ink">
                          Selected services
                        </span>{" "}
                      </section>
                      <p className="pl-10">
                        <span className="font-semibold">
                          Services requested:{" "}
                        </span>
                        {autoGeneratedSummary}
                      </p>
                    </div>
                  )}
                </section>
              </div>
            </SectionCard>

            <SectionCard
              title="Choose a Vendor (Optional)"
              iconBg="bg-success/20"
              desc="Pick a specific vendor to send this request directly to them,
                  or skip to let matching vendors respond."
              icon={<span className="text-sm font-semibold">2</span>}
              className="border border-surface-page shadow-md bg-white w-full"
            >
              <div>
                <div className="grid grid-cols-2 gap-3">
                  <button
                    type="button"
                    onClick={handleSelectSpecific}
                    className={`text-left flex items-center gap-3 p-4 rounded-md border transition-all ${
                      bookingMode === "specific"
                        ? "border-success bg-success/5"
                        : "border-border hover:border-primary/30"
                    }`}
                  >
                    <div
                      className={`w-5 h-5 rounded-full border-2 flex items-center justify-center shrink-0 ${
                        bookingMode === "specific"
                          ? "border-success bg-success"
                          : "border-border-input"
                      }`}
                    >
                      {bookingMode === "specific" && (
                        <div className="w-2.5 h-2.5 rounded-full bg-white" />
                      )}
                    </div>
                    <div className="w-9 h-9 rounded-lg bg-success/10 flex items-center justify-center shrink-0">
                      <Send size={16} className="text-success" />
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center justify-between gap-2 flex-wrap">
                        <h4 className="font-medium text-ink text-sm">
                          Send to a specific vendor
                        </h4>
                        <span className="text-[10px] font-medium px-2 py-0.5 rounded-full bg-success/10 text-success">
                          Recommended
                        </span>
                      </div>
                      <p className="text-xs text-ink-muted mt-0.5">
                        Your request will go directly to the selected vendor.
                      </p>
                    </div>
                  </button>

                  <button
                    type="button"
                    onClick={handleSelectBroadcast}
                    className={`text-left flex items-center gap-3 p-4 rounded-md border transition-all ${
                      bookingMode === "broadcast"
                        ? "border-primary bg-primary/5"
                        : "border-border hover:border-primary/30"
                    }`}
                  >
                    <div
                      className={`w-5 h-5 rounded-full border-2 flex items-center justify-center shrink-0 ${
                        bookingMode === "broadcast"
                          ? "border-primary"
                          : "border-border-input"
                      }`}
                    >
                      {bookingMode === "broadcast" && (
                        <div className="w-2.5 h-2.5 rounded-full bg-primary" />
                      )}
                    </div>
                    <div className="w-9 h-9 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
                      <Users size={16} className="text-primary" />
                    </div>
                    <div className="flex-1 min-w-0">
                      <h4 className="font-medium text-ink text-sm">
                        Let matching vendors respond
                      </h4>
                      <p className="text-xs text-ink-muted mt-0.5">
                        Your request will be shared with multiple relevant
                        vendors.
                      </p>
                    </div>
                  </button>
                </div>

                {bookingMode === "specific" && selectedVendor && (
                  <div className="flex flex-col gap-2 mt-4">
                    <VendorPickerCard
                      vendor={selectedVendor}
                      selectable={false}
                      onChangeVendor={openVendorPicker}
                      onRemoveVendor={() => setSelectedVendor(null)}
                    />
                    <div className="flex items-center gap-2 px-4 py-2.5 rounded-lg bg-primary/5 text-xs text-ink-muted">
                      <ShieldCheck
                        size={14}
                        className="text-primary-deep shrink-0"
                      />
                      You can change the vendor or choose matching vendors at
                      any time before submitting your request.
                    </div>
                  </div>
                )}

                {bookingMode === "specific" && !selectedVendor && (
                  <button
                    type="button"
                    onClick={openVendorPicker}
                    className="text-xs font-medium text-primary hover:underline mt-3"
                  >
                    Choose a vendor →
                  </button>
                )}
              </div>
            </SectionCard>

            <SectionCard
              title="Location"
              iconBg="bg-success/20"
              icon={<span className="text-sm font-semibold">3</span>}
              className="border border-surface-page shadow-md bg-white w-full"
            >
              <div className="flex flex-col gap-1">
                <div className="grid grid-cols-1 gap-4 mb-3">
                  <section>
                    <FieldTitle
                      label="Address"
                      htmlFor="house"
                      className="ml-1"
                      isRequired
                    />
                    <Input
                      placeholder="House / Flat No., Building, Street "
                      className="px-3 py-2 mt-1.5 "
                      value={address}
                      id="house"
                      onChange={(e) => setAddress(e.target.value)}
                    />
                  </section>
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <section>
                    <FieldTitle
                      label="Locality / Area"
                      htmlFor="locality"
                      className="ml-1"
                      isRequired
                    />
                    <Input
                      id="locality"
                      className="mt-1.5"
                      placeholder="E.g. Hinjewadi"
                      value={locality}
                      onChange={(e) => setLocality(e.target.value)}
                    />
                  </section>
                  <section>
                    <FieldTitle
                      label="City"
                      htmlFor="city"
                      className="ml-1"
                      isRequired
                    />
                    <Input
                      id="city"
                      className="mt-1.5"
                      placeholder="E.g. Pune"
                      value={city}
                      onChange={(e) => setCity(e.target.value)}
                    />
                  </section>
                  <section>
                    <FieldTitle
                      label="State"
                      htmlFor="state"
                      className="ml-1"
                      isRequired
                    />
                    <Input
                      id="state"
                      className="mt-1.5"
                      placeholder="E.g. Maharashtra"
                      value={state}
                      onChange={(e) => setState(e.target.value)}
                    />
                  </section>
                  <section>
                    <FieldTitle
                      label="Pincode"
                      htmlFor="pincode"
                      className="ml-1"
                      isRequired
                    />
                    <Input
                      id="pincode"
                      className="mt-1.5"
                      placeholder="E.g. 411057"
                      value={pincode}
                      onChange={(e) => setPincode(e.target.value)}
                    />
                  </section>
                </div>
              </div>
            </SectionCard>

            {/* 4. Preferred Schedule */}
            <SectionCard
              title="Preferred Schedule"
              iconBg="bg-success/20"
              icon={<span className="text-sm">4</span>}
              className="border border-surface-page shadow-md bg-white w-full"
            >
              <div>
                <div className="grid grid-cols-2 gap-3">
                  <input
                    type="date"
                    value={preferredDate}
                    onChange={(e) => setPreferredDate(e.target.value)}
                    className="px-3 py-2 rounded-lg border border-border-input text-sm"
                  />
                  <input
                    type="time"
                    value={preferredTime}
                    onChange={(e) => setPreferredTime(e.target.value)}
                    className="px-3 py-2 rounded-lg border border-border-input text-sm"
                  />
                </div>
                <p className="text-xs text-ink-muted mt-2">
                  Vendors will contact you to confirm the exact time.
                </p>
              </div>
            </SectionCard>

            {/* 5. Budget (Optional) */}
            <SectionCard
              title="Budget (Optional)"
              iconBg="bg-success/20"
              icon={<span className="text-sn">5</span>}
              className="border border-surface-page shadow-md bg-white w-full"
            >
              <div>
                <Input
                  placeholder="E.g. ₹1500 - ₹3000"
                  value={estimatedBudget}
                  onChange={(e) => setEstimatedBudget(e.target.value)}
                />
              </div>
            </SectionCard>

            <div className="flex justify-end gap-3">
              <Button
                onClick={handleSubmit}
                disabled={submitting}
                className="flex items-center gap-2 px-6 py-2.5 rounded-xl text-sm font-semibold
                               text-white transition-all disabled:opacity-40 disabled:cursor-not-allowed active:scale-[0.97] hover:shadow-xl"
                style={{ backgroundColor: "#16161D" }}
              >
                {submitting ? "Submitting..." : "Submit Request"}
              </Button>
            </div>
          </div>

          {/* Vendor picker modal */}
          <VendorPickerModal
            open={showVendorPicker}
            onClose={() => setShowVendorPicker(false)}
            vendors={vendorResults}
            loading={vendorsLoading}
            onConfirm={(vendor) => setSelectedVendor(vendor)}
          />

          <BookingConfirmModal
            open={showConfirm}
            onClose={() => setShowConfirm(false)}
            booking={confirmedBooking}
          />
        </section>
      </section>
    </section>
  );
}
